SLVSCODE-272 Add support for ${workspaceFolder} variable for compile commands
SonarSource/sonarlint-language-server pull request #132
Opened 2022-04-29 09:47 UTC by kirill-knize-sonarsource

2022-04-29 13:25 UTC, kirill-knize-sonarsource commented on src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java
> +    if (uri != null) {
Fix for the logging. Previously this line just silently skipped logging in case uri is null.

2022-04-29 14:04 UTC, henryju requested changes

2022-05-02 09:14 UTC, henryju requested changes

2022-05-02 09:14 UTC, henryju commented on src/main/java/org/sonarsource/sonarlint/ls/util/Utils.java
> +  public static boolean uriHasFileSchema(URI uri) {
You could possibly add a few unit tests for this method.

2022-05-02 09:14 UTC, henryju commented on src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java
> +    if(path.startsWith("/")) {
Please fix code style

2022-05-02 09:14 UTC, henryju commented on src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java
> +      return StringUtils.removeStart(path, "/");
I think you should handle Windows folder separator as well (backslash).

2022-05-02 12:54 UTC, henryju approved these changes
LGTM, well done!

2022-05-02 12:54 UTC, henryju commented on src/test/java/org/sonarsource/sonarlint/ls/util/UtilsTests.java
> +  void uriHasFileSchemaTest() {
:+1:

2022-05-02 15:34 UTC, merged