SLLS-122 support QuickFixes with notebooks
SonarSource/sonarlint-language-server pull request #195
Opened 2023-02-13 15:48 UTC by sophio-japharidze-sonarsource

2023-02-15 17:02 UTC, kirill-knize-sonarsource requested changes
Some cleanup needed.

2023-02-15 17:05 UTC, jblievremont commented on src/main/java/org/sonarsource/sonarlint/ls/AnalysisScheduler.java
> +      if (!Utils.uriHasFileScheme(f.getUri())) {
Pretty sure it's [scheme](https://en.wikipedia.org/wiki/List_of_URI_schemes) 😇

2023-02-16 09:02 UTC, jblievremont requested changes
From a pure functional point of view this seems to do the job.

I believe the code would be more robust and future-proof if it relied on the LSP-backed relationship between notebooks and cells, rather on what looks like VSCode-specific implementation details.

2023-02-16 13:23 UTC, kirill-knize-sonarsource approved these changes

2023-02-16 16:44 UTC, jblievremont approved these changes
LGTM 👍🏻

2023-02-17 08:04 UTC, merged