SLVSCODE-120 notify user if NodeCommandException
SonarSource/sonarlint-language-server pull request #29
Opened 2020-09-18 09:27 UTC by kirill-knize-sonarsource

2020-09-25 12:24 UTC, jblievremont requested changes
Almost there! Please see my comments.

2020-09-25 12:24 UTC, jblievremont commented on src/main/java/org/sonarsource/sonarlint/ls/log/LanguageClientLogOutput.java
> +      params.setMessage("JS/TS analyzer issue. Look at the log output for more details.");
```suggestion
      params.setMessage("JS/TS analysis failed. Please check the SonarLint Output for more details.");
```

2020-09-28 11:12 UTC, kirill-knize-sonarsource commented on src/main/java/org/sonarsource/sonarlint/ls/log/LanguageClientLogOutput.java
> +      ArrayList<MessageActionItem> actionItems = new ArrayList<>();
Done.

2020-09-28 11:13 UTC, kirill-knize-sonarsource commented on src/test/java/org/sonarsource/sonarlint/ls/log/LanguageClientLogOutputTests.java
> +    MessageActionItem actionItem = new MessageActionItem("Show SonarLint Output");
Done.

2020-09-28 11:13 UTC, kirill-knize-sonarsource commented on src/main/java/org/sonarsource/sonarlint/ls/log/LanguageClientLogOutput.java
> +      params.setMessage("JS/TS analyzer issue. Look at the log output for more details.");
Done.

2020-09-28 11:20 UTC, kirill-knize-sonarsource commented on src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java
> +      return null;
Done.

2020-09-28 15:39 UTC, jblievremont approved these changes
LGTM

2020-09-30 15:59 UTC, merged